services:
  - type: web
    name: golf-swing-analyzer
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: sk-... # or leave blank and set in the dashboard later
    plan: free
